# Generated by Django 6.0.6 on 2026-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_flat_free_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
