# Generated by Django 6.0.6 on 2026-06-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
