# Generated by Django 6.0.6 on 2026-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_platformsettings_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='popular_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
