import api from './api'

export const getAdminStats    = ()       => api.get('/orders/admin/stats/')
export const getAdminUsers    = (params) => api.get('/auth/admin/users/', { params })
export const updateAdminUser  = (id, data) => api.patch(`/auth/admin/users/${id}/`, data)
export const deleteAdminUser  = (id) => api.delete(`/auth/admin/users/${id}/`)
export const getAdminOrders   = (params) => api.get('/orders/admin/', { params })
export const getAdminProducts = (params) => api.get('/products/admin/', { params })
export const updateAdminProduct = (id, data) => api.patch(`/products/admin/${id}/`, data)
export const getAdminPayments = (params) => api.get('/payments/admin/', { params })
export const markAdminPaymentPaid = (id, data = {}) => api.post(`/payments/admin/${id}/mark-paid/`, data)
export const getAdminReviews  = (params) => api.get('/reviews/admin/', { params })
export const deleteAdminReview = (id) => api.delete(`/reviews/admin/${id}/`)
export const getAdminAds      = (params) => api.get('/ads/admin/', { params })
export const getAdminDisputes = (params) => api.get('/disputes/admin/', { params })
export const resolveAdminDispute = (id, data) => api.post(`/disputes/admin/${id}/resolve/`, data)
export const getAdminAnalyticsOverview = (params) => api.get('/analytics/admin/overview/', { params })
export const getAdminAnalyticsVendors = (params) => api.get('/analytics/admin/vendors/', { params })
export const getAdminAuditLogs = (params) => api.get('/internal/admin/audit-logs/', { params })
