# Generated by Django 6.0.6 on 2026-06-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_unfreeze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SALE', 'Vente'), ('COMMISSION', 'Commission'), ('PAYOUT', 'Retrait'), ('REFUND', 'Remboursement'), ('FREEZE', 'Gel'), ('AD_SPEND', 'Publicite'), ('UNFREEZE', 'Degel litige'), ('RELEASE', 'Dégel')], max_length=15),
        ),
    ]
