# Generated by Django 6.0.6 on 2026-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_type_maxlength'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, unique=True)),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile money'), ('BANK', 'Banque')], default='MOBILE_MONEY', max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte de versement plateforme',
                'verbose_name_plural': 'Compte de versement plateforme',
            },
        ),
    ]
